<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- Gazebo Colors -->
    <gazebo reference="chassis_link">
        <material>
            Gazebo/Red
        </material>
    </gazebo>

    <!-- Chassis Link -->
    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
                <origin xyz="${chassis_length/2} 0.0 ${chassis_height/2}" rpy="0.0 0.0 0.0"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
                <origin xyz="${chassis_length/2} 0.0 ${chassis_height/2}" rpy="0.0 0.0 0.0"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="2" x="0.4" y="0.3" z="0.11"/>
        <origin xyz="${chassis_length/2} 0.0 ${chassis_height/2}" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="-0.2 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>